export {
  defineObject,
  defineLink,
  defineAction,
  defineOntology,
  createRuntime,
  Runtime,
  declarations,
  reject,
  modify,
  create,
  link,
  unlink,
} from './core.js'
export type {
  ObjectTypeDef,
  LinkTypeDef,
  ActionDef,
  ActionCtx,
  OntologyDef,
  ObjectName,
  LinkName,
  ActionName,
  Direction,
  ObjectOf,
  ObjectInstance,
  ObjectFilter,
  LinksFrom,
  LinkDirections,
  LinkTarget,
  TraverseOptions,
  ParamsOf,
  Violation,
  Edit,
  ActionResult,
  AuditEntry,
  WritebackAdapter,
} from './core.js'
export { buildMcpServer } from './mcp.js'
