export {
  defineObject,
  defineLink,
  defineAction,
  defineOntology,
  createRuntime,
  Runtime,
  reject,
  modify,
  create,
  remove,
  link,
  unlink,
  isTargeted,
} from './core.js'
export type {
  ObjectTypeDef,
  LinkTypeDef,
  ActionDef,
  TargetlessActionDef,
  AnyActionDef,
  ActionCtx,
  TargetlessActionCtx,
  OntologyDef,
  Violation,
  Edit,
  ActionResult,
  AuditEntry,
  WritebackAdapter,
} from './core.js'
export { buildMcpServer } from './mcp.js'
